Title:  AI Agents Jax
description: AI-powered agents for small businesses 
remote_theme: pages-themes/modernist@v0.2.0

body {
      background-image: url("https://raw.githubusercontent.com/jgjgcrewsmaker/aiagentsjax/master/images/bridge.jpg");
      /* ... other styles here */
    }
